a = input('Digite algo: ')
print('O tipo primitivo desse valor é : ', type(a))
print('So tem espaços? :', a.isspace())
print('É um numero? :', a.isnumeric())
print('É alfabético? :', a.isalpha())
print('É alfanumerico? :', a.isalnum())
print('esta capitalizada? :', a.istitle())
print('Tem apenas letras maiuscula? :', a.isupper())
print('Tem apenas letras minusculas? :', a.islower())
