nome = str(input(' Digite seu nome completo :'))
dividido = nome.split()
total = ''.join(dividido)
primeiro = len(dividido[0])
valor = len(total)

print('Analizando seu nome...')
print('Seu nome em maiusculas é {} !'.format(nome.upper()))
print('Seu nome em minusculas é {} !'.format(nome.lower()))
print('Seu nome tem ao todo {} letras !'.format(valor))
print('Seu primeiro nome é {} e ele tem {} letras !'.format(dividido[0], primeiro))
