times = ('botafogo', 'falmengo', 'palmeiras', 'fortaleza', 'cruzeiro', 'são paulo', 'bahia', 'ca paranaense'
         'atletico mineiro', 'red bull bragantino', 'vasco gama', 'criciúma', 'ec juventude', 'gremio', 'ec vitoria ba'
         'internacional rs', 'fluminense rj', 'corinthians', 'cuiabá', 'ac goianiense')
print('-=' * 18)
print(f'A lista do brasileirão 2024: {times}')
print('-=' * 18)
print('os primeiros 5 colocados são :')
print(times[:6])
print('-=' * 18)
print('os 4 ultimos são :')
print(times[-4:])
print('-=' * 18)
print('ordem alfabetica são: ')
print(sorted(times))
print('-=' * 18)
#print('a posição do palmeras é : ')
#posicao = (times.index('palmeiras'))
#print(f'Ele esta na {posicao + 1}° posição ')
print(f'A posição do palmeiras é : {times.index('palmeiras') + 1}')
